In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [9]:
##sentences
sentences = ['the cat sat on the mat',
             'the dog sat on the log',
             'the cat sat on the log',
             'The dog is barking']
sentences

['the cat sat on the mat',
 'the dog sat on the log',
 'the cat sat on the log',
 'The dog is barking']

In [10]:
##Define vocabulary size
vocab_size = 1000


In [11]:
###one hot representation of sentences
one_hot_representations = [one_hot(word, vocab_size) for word in sentences]
one_hot_representations

[[897, 670, 662, 292, 897, 533],
 [897, 199, 662, 292, 897, 112],
 [897, 670, 662, 292, 897, 112],
 [897, 199, 66, 302]]

In [12]:
sentences

['the cat sat on the mat',
 'the dog sat on the log',
 'the cat sat on the log',
 'The dog is barking']

In [13]:
##word embedding reprensentation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [19]:
sent_length = 5
embedded_docs = pad_sequences(one_hot_representations, padding='pre', maxlen=sent_length)

In [20]:
print(embedded_docs)

[[670 662 292 897 533]
 [199 662 292 897 112]
 [670 662 292 897 112]
 [  0 897 199  66 302]]


In [21]:
##feature representation using embedding layer
dim=10


In [23]:
model=Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

c:\Users\DELL\DEEP LEARNING NLP\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [24]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 437ms/step


array([[[-2.08640937e-02, -1.42017007e-02,  4.26458195e-03,
          1.77582540e-02,  8.70532915e-03,  2.31255405e-02,
         -8.61674547e-03,  3.51852886e-02, -3.32085378e-02,
          2.89431475e-02],
        [ 7.79664516e-03,  1.95062160e-03, -3.36856619e-02,
          9.05593485e-03,  2.23172642e-02,  7.72650167e-03,
         -1.08553991e-02, -1.37034282e-02, -1.08623020e-02,
          3.67591269e-02],
        [-4.04537693e-02, -1.75852999e-02,  6.44761324e-03,
          4.05454673e-02,  4.46034409e-02,  1.84021704e-02,
          3.62729095e-02, -1.06747150e-02, -3.16875726e-02,
         -4.46689986e-02],
        [-2.84789335e-02, -1.32418275e-02, -1.92660820e-02,
          2.45397203e-02,  2.01303475e-02,  1.44153722e-02,
         -4.35366407e-02,  1.04463100e-02,  1.42580383e-02,
          1.89889409e-02],
        [-3.19483057e-02,  2.29179300e-02, -3.36599350e-03,
          2.17071213e-02,  9.45227221e-03,  5.85462898e-03,
         -1.74203739e-02,  4.07788642e-02,  2.290756

In [26]:
embedded_docs[0]

array([670, 662, 292, 897, 533], dtype=int32)